name: Ingest GitHub Resource
description: Capture a GitHub repository or bookmark into the research corpus.
title: "[GitHub] "
labels:
  - ingest:github
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: Repository or resource URL.
      placeholder: https://github.com/owner/repo
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: Friendly name for this entry inside the corpus.
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - threejs
        - react-three-fiber
        - webgl
        - shaders
        - graphics
        - blender
        - design
        - tooling
        - ai-tools
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated list (e.g. threejs,instancing,performance)
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Optional summary or notes.
      render: markdown
  - type: textarea
    id: readme
    attributes:
      label: README / Description snapshot
      description: Paste relevant README sections or notes so the Action can store them under notes/.
      render: markdown
